sudo: true
language: php
php:
  - 7.1

matrix:
    fast_finish: true

before_install:
  - export SCRIPT_DIR=$TRAVIS_BUILD_DIR/.scripts
  - export DRUPAL_DIR=/opt/drupal

install:
  - $SCRIPT_DIR/travis_setup.sh
  - git -C "$TRAVIS_BUILD_DIR" checkout -b travis-testing
  - cd $DRUPAL_DIR; composer config repositories.local path "$TRAVIS_BUILD_DIR"
  - composer require "islandora/islandora:dev-travis-testing as dev-8.x-1.x" --prefer-source
  - cd web; drush en -y islandora

script:
  - $SCRIPT_DIR/line_endings.sh $TRAVIS_BUILD_DIR
  - phpcs --standard=Drupal --extensions=php,module,inc,install,test,profile,theme,css,info $TRAVIS_BUILD_DIR
  - phpcpd --names *.module,*.inc,*.test,*.php $TRAVIS_BUILD_DIR
  - phpcovrunner start
  - php core/scripts/run-tests-cov.sh --verbose --php `which php` islandora

after_success:
  - phpcovrunner stop
  - bash <(curl -s https://codecov.io/bash)
